export const DECISION_REASONS = [
  "WITHIN_POLICY",
  "APP_NOT_FOUND",
  "ORIGIN_NOT_ALLOWED",
  "SESSION_NOT_FOUND",
  "SESSION_PENDING_APPROVAL",
  "SESSION_EXPIRED",
  "SESSION_REVOKED",
  "ACTION_NOT_ALLOWED",
  "ACTION_EXPLICITLY_DENIED",
  "ASSET_NOT_ALLOWED",
  "AMOUNT_EXCEEDS_SESSION_LIMIT",
  "AMOUNT_EXCEEDS_DAILY_LIMIT",
  "APPROVAL_REQUIRED",
  "PAYMENT_NOT_OWNED_BY_SESSION",
  "INVALID_REQUEST",
  "UPSTREAM_FIBER_ERROR",
] as const;

export type DecisionReason = (typeof DECISION_REASONS)[number];

export type Decision = "allowed" | "blocked";
